"""report/reporter.py – Renders audit findings as HTML, JSON, or Markdown."""

from __future__ import annotations
import json
from collections import Counter
from dataclasses import asdict
from typing import Any


_STATUS_COLOUR = {
    "FAIL": "#c0392b",
    "WARN": "#e67e22",
    "PASS": "#27ae60",
    "INFO": "#2980b9",
}


class Reporter:
    def __init__(self, findings: list[Any]):
        self._findings = findings

    def summary(self) -> dict[str, int]:
        return dict(Counter(f.status for f in self._findings))

    def render(self, fmt: str = "html") -> str:
        if fmt == "json":
            return self._json()
        if fmt == "markdown":
            return self._markdown()
        return self._html()

    # ── JSON ──────────────────────────────────────────────────────────────────
    def _json(self) -> str:
        return json.dumps(
            {"summary": self.summary(), "findings": [asdict(f) for f in self._findings]},
            indent=2,
        )

    # ── Markdown ──────────────────────────────────────────────────────────────
    def _markdown(self) -> str:
        totals = self.summary()
        lines  = [
            "# Kubernetes Security Audit Report",
            "",
            "## Summary",
            "",
            f"| Status | Count |",
            f"|--------|-------|",
        ]
        for status in ("FAIL", "WARN", "PASS", "INFO"):
            lines.append(f"| {status} | {totals.get(status, 0)} |")
        lines += ["", "## Findings", ""]
        for f in self._findings:
            lines += [
                f"### [{f.status}] {f.control_id} – {f.title}",
                "",
                f"**Detail:** {f.detail}",
                "",
            ]
            if f.remediation:
                lines += [f"**Remediation:** {f.remediation}", ""]
            if f.namespace:
                lines += [f"**Namespace:** `{f.namespace}`", ""]
            if f.tags:
                lines += [f"**Tags:** {', '.join(f'`{t}`' for t in f.tags)}", ""]
            lines.append("---")
        lines.append("_Generated by [k8s-security-auditor](https://github.com/AnkSingh2-secOps/k8s-security-auditor)_")
        return "\n".join(lines)

    # ── HTML ──────────────────────────────────────────────────────────────────
    def _html(self) -> str:
        totals = self.summary()
        rows   = "\n".join(self._finding_row(f) for f in self._findings)
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>K8s Security Audit Report</title>
<style>
  body {{ font-family: 'Segoe UI', sans-serif; margin: 2em; background: #f5f6fa; color: #2d3436; }}
  h1   {{ color: #2d3436; }}
  .summary {{ display: flex; gap: 1em; margin: 1em 0 2em; }}
  .pill {{ padding: .4em 1.2em; border-radius: 999px; font-weight: bold; color: #fff; font-size: .9em; }}
  table {{ width: 100%; border-collapse: collapse; background: #fff; box-shadow: 0 1px 4px rgba(0,0,0,.1); }}
  th, td {{ padding: .7em 1em; text-align: left; border-bottom: 1px solid #dfe6e9; }}
  th {{ background: #dfe6e9; }}
  .FAIL {{ color: {_STATUS_COLOUR['FAIL']}; font-weight: bold; }}
  .WARN {{ color: {_STATUS_COLOUR['WARN']}; font-weight: bold; }}
  .PASS {{ color: {_STATUS_COLOUR['PASS']}; font-weight: bold; }}
  .INFO {{ color: {_STATUS_COLOUR['INFO']}; font-weight: bold; }}
  code {{ background: #f1f2f6; padding: .1em .4em; border-radius: 3px; font-size: .85em; }}
  footer {{ margin-top: 2em; font-size: .8em; color: #636e72; }}
</style>
</head>
<body>
<h1>Kubernetes Security Audit Report</h1>
<div class="summary">
  {''.join(f'<span class="pill" style="background:{_STATUS_COLOUR.get(s, "#636e72")}">{s}: {totals.get(s,0)}</span>' for s in ("FAIL","WARN","PASS","INFO"))}
</div>
<table>
  <thead>
    <tr><th>Status</th><th>Control</th><th>Title</th><th>Resource / Namespace</th><th>Detail</th><th>Remediation</th></tr>
  </thead>
  <tbody>
{rows}
  </tbody>
</table>
<footer>Generated by <a href="https://github.com/AnkSingh2-secOps/k8s-security-auditor">k8s-security-auditor</a></footer>
</body>
</html>"""

    @staticmethod
    def _finding_row(f) -> str:
        loc = f.namespace or f.resource or "-"
        rem = f.remediation or "-"
        return (
            f'    <tr>'
            f'<td class="{f.status}">{f.status}</td>'
            f'<td><code>{f.control_id}</code></td>'
            f'<td>{f.title}</td>'
            f'<td><code>{loc}</code></td>'
            f'<td>{f.detail}</td>'
            f'<td>{rem}</td>'
            f'</tr>'
        )
